ssh_authorized_keys:
- github:toraxe
hostname: k3s-1
init_cmd:
- "echo hello, init command"
boot_cmd:
- "echo hello, boot command"
run_cmd:
- "echo hello, run command"

k3os:
  modules:
  - nvme
  k3s_args:
  - server
  password: rancher
