ssh_authorized_keys:
- github:toraxe
hostname: server-manager
init_cmd:
- "echo hello, init command"
boot_cmd:
- "echo hello, boot command"
run_cmd:
- "echo hello, run command"

k3os:
  modules:
  - kvm
  - nvme
  k3s_args:
  - server
